//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adherent3_EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class adherent
    {
        public int idAdherent { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public Nullable<int> TypeAdhesion { get; set; }
    
        public virtual typeadhesion typeadhesion1 { get; set; }
    }
}
