//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adherent3_EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class typeadhesion
    {
        public typeadhesion()
        {
            this.adherent = new HashSet<adherent>();
        }
    
        public int idTypeAdhesion { get; set; }
        public string Libelle { get; set; }
        public Nullable<int> Tarif { get; set; }
    
        public virtual ICollection<adherent> adherent { get; set; }
    }
}
